# Generated by Django 4.0.3 on 2022-03-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_students_firstname_alter_students_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='student',
        ),
    ]
