# Generated by Django 4.0.3 on 2022-03-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_session_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='fullname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
