# Generated by Django 4.0.3 on 2022-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_session_currduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='currDuration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
