# Generated by Django 4.0.3 on 2022-03-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_session_currduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='totalHours',
            field=models.TimeField(),
        ),
    ]
