# Generated by Django 4.0.3 on 2022-03-16 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_students_totalhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='totalHours',
            field=models.TimeField(default=datetime.time(0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
