# Generated by Django 4.0.3 on 2022-03-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_students_totalhours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='totalHours',
        ),
        migrations.AddField(
            model_name='students',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
